services:
  - type: web
    name: proyecto-final-ml
    env: python
    plan: free
    rootDir: Proyecto_Final
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
    healthCheckPath: /

